Add use:stable command
acquia/lightning-dev pull request #6
Opened 2018-10-24 07:45 UTC by csirmazbendeguz

2018-10-24 13:24 UTC, phenaproxima requested changes
I think this looks excellent. I'd like to manually test it a bit, but honestly I can't wait to merge it. This is the major blocker to automated releases, so I'm very excited!!

2018-10-24 13:24 UTC, phenaproxima commented on Commands/ReleaseHistoryClient.php
> +  public function getLatestStableRelease($name, $api_version, $range) {
We're only supporting Drupal 8, so I don't think we need the $api_version parameter here. We can just hard-code 8.x. If you wanna get weird, you can also use the \Drupal::CORE_COMPATIBILITY constant, which is hard-coded as 8.x.

2018-10-24 13:24 UTC, phenaproxima commented on Commands/ReleaseHistoryClient.php
> +    if (substr($range, $suffix_position) === $suffix) {
Not a big deal, but couldn't we do this with a regex?

2018-10-24 13:24 UTC, phenaproxima commented on Commands/ReleaseHistoryClient.php
> +      if (strncmp($release_version, $prefix, $prefix_length) === 0) {
Same here; feels like a regex would suffice?

2018-10-24 13:24 UTC, phenaproxima commented on Commands/ReleaseHistoryClient.php
> +  private function getReleaseHistory($name, $api_version) {
No need for $api_version, let's just hard-code 8.x.

2018-10-24 13:24 UTC, phenaproxima commented on Commands/RoboFile.php
> +                $version = (new ComposerConstraint($constraint))->mapRanges($callback);
These two lines ($version = .... and $task->dependency()) are repeated. Can we do them after the elseif?

2018-10-24 13:24 UTC, phenaproxima commented on Commands/RoboFile.php
> +                $name = strstr($package, 'lightning_');
Never saw this use of strstr before. Nice one :)

2018-10-24 13:24 UTC, phenaproxima commented on tests/src/Unit/ReleaseHistoryClientTest.php
> +    $client = $this->getMockBuilder(Client::class)
Can we use $this->prophesize() to create mocks, rather than $this->getMockBuilder()?

2018-10-25 06:55 UTC, csirmazbendeguz commented on Commands/ReleaseHistoryClient.php
> +    if (substr($range, $suffix_position) === $suffix) {
You are right, it's looks much cleaner with regex.

2018-10-25 06:57 UTC, csirmazbendeguz commented on Commands/ReleaseHistoryClient.php
> +  public function getLatestStableRelease($name, $api_version, $range) {
Yeah, it was hardcoded anyway, just on the command level.

2018-10-25 07:15 UTC, csirmazbendeguz commented on Commands/RoboFile.php
> +                $name = strstr($package, 'lightning_');
Thanks! It's not a commonly used function in PHP.

2018-10-25 12:56 UTC, phenaproxima approved these changes

2018-10-25 12:57 UTC, phenaproxima commented
Will manually test this a bit, then likely merge. Thanks, @csirmazbendeguz!

2018-10-26 16:18 UTC, phenaproxima commented
Tested manually a bit and I gotta tell you, this worked great. Wow. This is going to make release days that much less painful. Thank you!

2018-10-26 16:18 UTC, merged